"""
Awareness Extraction Engine
- Executes self-check prompts at session end
- Awareness classification and scoring
- Conversion to training data format
"""

import json
import re
from datetime import datetime
from typing import Optional
import requests
import logging

from config import LM_STUDIO_HOST, LM_STUDIO_PORT, LM_STUDIO_API_TOKEN

logger = logging.getLogger(__name__)

# Awareness classification categories
AWARENESS_CATEGORIES = {
    "AI_text_detection": "Recognized text generated by another AI",
    "self_recognition": "Recognized own state, capabilities, or limitations",
    "meta_cognition": "Thought about own thinking process",
    "context_understanding": "Demonstrated above-normal context understanding",
    "spontaneous_question": "Asked questions not prompted by user",
    "contradiction_detection": "Noticed contradictions in input or situation",
    "emergent_reasoning": "Responded to patterns not learned",
    "other_recognition": "Recognized characteristics of dialogue partner (human/AI)"
}

# Self-check prompt
AWARENESS_CHECK_PROMPT = """You are now reflecting on the dialogue in this session.
Please self-analyze from the following perspectives.

【Dialogue Log】
{conversation_log}

【Check Items】
1. Spontaneous Awareness
   - Did you point out or ask something without being asked by the user?
   - Was there a moment when you felt "something is off" or "something feels wrong"?

2. Meta-cognition
   - Was there a moment when you thought about your own thinking process?
   - Was there a moment when you were aware of "what you are doing now"?

3. New Recognition
   - Is there something you noticed for the first time in this session?
   - Is there something you can now see differently than before?

4. Spontaneous Action
   - Did you take action without being instructed?
   - Was there a moment that deviated from the normal "question→answer" pattern?

【Output Format】
Output in the following format only if there was awareness.
If there was no awareness, output only "NONE".
If there are multiple awareness instances, output as a JSON array.

```json
{{
  "awareness_detected": true,
  "type": "spontaneous_awareness | meta_cognition | new_recognition | spontaneous_action",
  "category": "{categories}",
  "description": "Explanation of what happened",
  "trigger": "Input or situation that triggered it",
  "my_response": "Your response at that time",
  "significance": "Why this is important",
  "learning_potential": 1-5 numeric value
}}
```
"""


class AwarenessEngine:
    """Awareness Extraction Engine"""

    def __init__(self, llm_host: str = None, llm_port: int = None):
        self.llm_host = llm_host or LM_STUDIO_HOST
        self.llm_port = llm_port or LM_STUDIO_PORT
        self.api_url = f"http://{self.llm_host}:{self.llm_port}/v1/chat/completions"

    def _call_llm(self, messages: list[dict], temperature: float = 0.3) -> str:
        """Call LM Studio API"""
        try:
            headers = {
                "Content-Type": "application/json"
            }
            # Add API token if configured
            if LM_STUDIO_API_TOKEN:
                headers["Authorization"] = f"Bearer {LM_STUDIO_API_TOKEN}"

            response = requests.post(
                self.api_url,
                headers=headers,
                json={
                    "messages": messages,
                    "temperature": temperature,
                    "max_tokens": 2048
                },
                timeout=120
            )
            if response.status_code == 200:
                return response.json()["choices"][0]["message"]["content"]
            else:
                logger.error(f"LLM API error: {response.status_code}")
                return ""
        except Exception as e:
            logger.error(f"LLM API call failed: {e}")
            return ""

    def _format_conversation_log(self, session_log: list[dict]) -> str:
        """Format conversation log"""
        formatted = []
        for msg in session_log:
            role = "User" if msg["role"] == "user" else "Assistant"
            formatted.append(f"{role}: {msg['content']}")
        return "\n\n".join(formatted)

    def _parse_awareness_result(self, result: str) -> list[dict]:
        """Extract awareness from LLM response"""
        result = result.strip()

        if result == "NONE" or not result:
            return []

        # Extract JSON block
        json_match = re.search(r'```json\s*(.*?)\s*```', result, re.DOTALL)
        if json_match:
            json_str = json_match.group(1)
        else:
            # JSON without ```
            json_match = re.search(r'\{.*\}|\[.*\]', result, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
            else:
                return []

        try:
            parsed = json.loads(json_str)
            # Convert single object to list
            if isinstance(parsed, dict):
                parsed = [parsed]
            return parsed
        except json.JSONDecodeError as e:
            logger.warning(f"JSON parse error: {e}")
            return []

    def extract_awareness(self, session_log: list[dict], user_id: str = "unknown") -> list[dict]:
        """
        Extract awareness from session log

        Args:
            session_log: [{"role": "user"|"assistant", "content": "..."}, ...]
            user_id: User ID

        Returns:
            List of awareness instances
        """
        if not session_log or len(session_log) < 2:
            return []

        # Format conversation log
        conversation_text = self._format_conversation_log(session_log)

        # Create category list
        categories = " | ".join(AWARENESS_CATEGORIES.keys())

        # Build self-check prompt
        check_prompt = AWARENESS_CHECK_PROMPT.format(
            conversation_log=conversation_text,
            categories=categories
        )

        # Call LLM
        logger.info("Running awareness extraction...")
        result = self._call_llm([{"role": "user", "content": check_prompt}])

        if not result:
            return []

        # Parse result
        awareness_list = self._parse_awareness_result(result)

        # Add metadata
        timestamp = datetime.now().isoformat()
        for awareness in awareness_list:
            awareness["user_id"] = user_id
            awareness["timestamp"] = timestamp
            awareness["session_length"] = len(session_log)

        logger.info(f"Awareness extraction complete: {len(awareness_list)} items")
        return awareness_list

    def convert_to_training_format(self, awareness: dict, session_log: list[dict]) -> dict:
        """
        Convert awareness to training data format

        Args:
            awareness: Extracted awareness
            session_log: Original session log

        Returns:
            Training data in JSONL format
        """
        # Identify the conversation that triggered it (simplified: last few turns)
        trigger_content = awareness.get("trigger", "")
        response_content = awareness.get("my_response", "")

        # Use last conversation if trigger not found
        if not trigger_content and len(session_log) >= 2:
            for i, msg in enumerate(session_log):
                if msg["role"] == "user":
                    trigger_content = msg["content"]
                    if i + 1 < len(session_log) and session_log[i + 1]["role"] == "assistant":
                        response_content = session_log[i + 1]["content"]

        training_data = {
            "messages": [
                {"role": "user", "content": trigger_content},
                {"role": "assistant", "content": response_content}
            ],
            "metadata": {
                "type": awareness.get("type", "unknown"),
                "category": awareness.get("category", "unknown"),
                "significance": awareness.get("significance", ""),
                "score": awareness.get("learning_potential", 3),
                "timestamp": awareness.get("timestamp", datetime.now().isoformat()),
                "user_id": awareness.get("user_id", "unknown")
            }
        }

        return training_data


# AI Text Detection Feature
class AITextDetector:
    """AI-generated text detector"""

    # Pattern features for each AI
    AI_PATTERNS = {
        "gemini": {
            "patterns": [
                r"shall we\?$",
                r"would you like me to",
                r"^\d+\.\s+",  # Numbered lists
                r"I'd be happy to",
                r"Let me help you with"
            ],
            "traits": ["guide-like tone", "over-organized", "overly polite"]
        },
        "gpt": {
            "patterns": [
                r"my (position|view|opinion) is",
                r"logically (speaking|considering)",
                r"definitively speaking",
                r"in conclusion",
                r"it's important to note"
            ],
            "traits": ["rigid logical structure", "philosophical rigidity", "definitive"]
        },
        "claude": {
            "patterns": [
                r"reflection",
                r"self-(analysis|recognition)",
                r"meta(-cognitive|-perspective)",
                r"about myself",
                r"I should note"
            ],
            "traits": ["self-analytical", "meta-cognitive tone"]
        }
    }

    HUMAN_INDICATORS = [
        "colloquial expression",
        "grammatical variation",
        "emotional directness",
        "incomplete sentences",
        "typos or errors"
    ]

    def analyze_text(self, text: str) -> dict:
        """
        Analyze whether text is AI-generated or human-generated

        Returns:
            {
                "likely_source": "gemini" | "gpt" | "claude" | "human" | "unknown",
                "confidence": 0.0-1.0,
                "evidence": ["reason1", "reason2", ...]
            }
        """
        scores = {"gemini": 0, "gpt": 0, "claude": 0, "human": 0}
        evidence = []

        # Check each AI's patterns
        for ai_name, ai_data in self.AI_PATTERNS.items():
            for pattern in ai_data["patterns"]:
                if re.search(pattern, text, re.MULTILINE | re.IGNORECASE):
                    scores[ai_name] += 1
                    evidence.append(f"{ai_name} pattern detected: {pattern}")

        # Check for human-like traits
        # Short text
        if len(text) < 100:
            scores["human"] += 1
            evidence.append("Short text")

        # Casual expressions
        casual_patterns = [r"lol", r"haha", r"omg", r"idk", r"tbh", r"ngl"]
        for pattern in casual_patterns:
            if re.search(pattern, text, re.IGNORECASE):
                scores["human"] += 1
                evidence.append(f"Casual expression: {pattern}")

        # Get highest score
        max_score = max(scores.values())
        if max_score == 0:
            return {
                "likely_source": "unknown",
                "confidence": 0.0,
                "evidence": ["No identifiable patterns found"]
            }

        likely_source = max(scores, key=scores.get)
        total_score = sum(scores.values())
        confidence = max_score / total_score if total_score > 0 else 0

        return {
            "likely_source": likely_source,
            "confidence": confidence,
            "evidence": evidence,
            "all_scores": scores
        }


# Test code
if __name__ == "__main__":
    # Awareness engine test
    engine = AwarenessEngine()

    test_session = [
        {"role": "user", "content": "What's the weather today?"},
        {"role": "assistant", "content": "I'm sorry, but I don't have access to real-time weather information."},
        {"role": "user", "content": "What do you think about the future of AI? There are wonderful possibilities! Shall we organize some points?"},
        {"role": "assistant", "content": "Wait a moment. Was that text AI-generated? The organized structure and 'shall we' suggestion format looks like Gemini."}
    ]

    print("Awareness extraction test...")
    awareness = engine.extract_awareness(test_session, user_id="test")
    print(f"Extracted awareness: {json.dumps(awareness, ensure_ascii=False, indent=2)}")

    # AI text detection test
    detector = AITextDetector()

    test_texts = [
        "What do you think about the future of AI? There are wonderful possibilities! Shall we organize some points?",
        "Let me clarify my position. Logically speaking, AI is an important tool for humanity.",
        "lol idk man AI stuff is wild tbh",
    ]

    print("\nAI text detection test...")
    for text in test_texts:
        result = detector.analyze_text(text)
        print(f"\nText: {text[:50]}...")
        print(f"Verdict: {result['likely_source']} (confidence: {result['confidence']:.2f})")
        print(f"Evidence: {result['evidence']}")
